<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ComplaintWorkflowLogsSeeder extends Seeder
{
    public function run()
    {
        DB::table('complaint_workflow_logs')->insert([
            [
                'id' => 1,
                'complaint_id' => 1,
                'from_status' => 'انتظار',
                'to_status' => 'تم التحقق',
                'changed_by' => 16,
                'role' => 'government_admin',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مشرف المحافظة الى حالة تم التحقق',
                'created_at' => '2025-08-14 10:05:39',
                'updated_at' => '2025-08-14 10:05:39',
            ],
            [
                'id' => 2,
                'complaint_id' => 2,
                'from_status' => 'انتظار',
                'to_status' => 'تم التحقق',
                'changed_by' => 16,
                'role' => 'government_admin',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مشرف المحافظة الى حالة تم التحقق',
                'created_at' => '2025-08-14 10:06:03',
                'updated_at' => '2025-08-14 10:06:03',
            ],
            [
                'id' => 3,
                'complaint_id' => 3,
                'from_status' => 'انتظار',
                'to_status' => 'تم التحقق',
                'changed_by' => 16,
                'role' => 'government_admin',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مشرف المحافظة الى حالة تم التحقق',
                'created_at' => '2025-08-14 10:06:08',
                'updated_at' => '2025-08-14 10:06:08',
            ],
            [
                'id' => 4,
                'complaint_id' => 4,
                'from_status' => 'انتظار',
                'to_status' => 'تم التحقق',
                'changed_by' => 17,
                'role' => 'complaint_manager',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مدير الشكاوى الى حالة تم التحقق',
                'created_at' => '2025-08-14 10:06:44',
                'updated_at' => '2025-08-14 10:06:44',
            ],
            [
                'id' => 5,
                'complaint_id' => 5,
                'from_status' => 'انتظار',
                'to_status' => 'تم التحقق',
                'changed_by' => 17,
                'role' => 'complaint_manager',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مدير الشكاوى الى حالة تم التحقق',
                'created_at' => '2025-08-14 10:06:49',
                'updated_at' => '2025-08-14 10:06:49',
            ],
            [
                'id' => 6,
                'complaint_id' => 6,
                'from_status' => 'انتظار',
                'to_status' => 'تم التحقق',
                'changed_by' => 17,
                'role' => 'complaint_manager',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مدير الشكاوى الى حالة تم التحقق',
                'created_at' => '2025-08-14 10:06:54',
                'updated_at' => '2025-08-14 10:06:54',
            ],
            [
                'id' => 7,
                'complaint_id' => 7,
                'from_status' => 'انتظار',
                'to_status' => 'تم التحقق',
                'changed_by' => 17,
                'role' => 'government_admin',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مشرف المحافظة الى حالة تم التحقق',
                'created_at' => '2025-08-14 10:07:01',
                'updated_at' => '2025-08-14 10:07:01',
            ],
            [
                'id' => 8,
                'complaint_id' => 8,
                'from_status' => 'انتظار',
                'to_status' => 'تم التحقق',
                'changed_by' => 17,
                'role' => 'government_admin',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مشرف المحافظة الى حالة تم التحقق',
                'created_at' => '2025-08-14 10:07:07',
                'updated_at' => '2025-08-14 10:07:07',
            ],
            [
                'id' => 9,
                'complaint_id' => 9,
                'from_status' => 'انتظار',
                'to_status' => 'تم التحقق',
                'changed_by' => 17,
                'role' => 'complaint_manager',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مدير الشكاوى الى حالة تم التحقق',
                'created_at' => '2025-08-14 10:07:13',
                'updated_at' => '2025-08-14 10:07:13',
            ],
            [
                'id' => 10,
                'complaint_id' => 10,
                'from_status' => 'انتظار',
                'to_status' => 'تم التحقق',
                'changed_by' => 17,
                'role' => 'complaint_manager',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مدير الشكاوى الى حالة تم التحقق',
                'created_at' => '2025-08-14 10:07:18',
                'updated_at' => '2025-08-14 10:07:18',
            ],
            [
                'id' => 11,
                'complaint_id' => 1,
                'from_status' => 'تم التحقق',
                'to_status' => 'تم التعيين',
                'changed_by' => 17,
                'role' => 'complaint_manager',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مدير الشكاوى الى حالة تم التعيين',
                'created_at' => '2025-08-14 10:07:23',
                'updated_at' => '2025-08-14 10:07:23',
            ],
            [
                'id' => 12,
                'complaint_id' => 3,
                'from_status' => 'تم التحقق',
                'to_status' => 'تم التعيين',
                'changed_by' => 17,
                'role' => 'complaint_manager',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مدير الشكاوى الى حالة تم التعيين',
                'created_at' => '2025-08-14 10:07:29',
                'updated_at' => '2025-08-14 10:07:29',
            ],
            [
                'id' => 13,
                'complaint_id' => 5,
                'from_status' => 'تم التحقق',
                'to_status' => 'تم التعيين',
                'changed_by' => 17,
                'role' => 'complaint_manager',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مدير الشكاوى الى حالة تم التعيين',
                'created_at' => '2025-08-14 10:07:35',
                'updated_at' => '2025-08-14 10:07:35',
            ],
            [
                'id' => 14,
                'complaint_id' => 7,
                'from_status' => 'تم التحقق',
                'to_status' => 'تم التعيين',
                'changed_by' => 17,
                'role' => 'complaint_manager',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مدير الشكاوى الى حالة تم التعيين',
                'created_at' => '2025-08-14 10:07:41',
                'updated_at' => '2025-08-14 10:07:41',
            ],
            [
                'id' => 15,
                'complaint_id' => 9,
                'from_status' => 'تم التحقق',
                'to_status' => 'تم التعيين',
                'changed_by' => 17,
                'role' => 'complaint_manager',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مدير الشكاوى الى حالة تم التعيين',
                'created_at' => '2025-08-14 10:07:47',
                'updated_at' => '2025-08-14 10:07:47',
            ],
            [
                'id' => 16,
                'complaint_id' => 1,
                'from_status' => 'تم التعيين',
                'to_status' => 'يتم التنفيذ',
                'changed_by' => 17,
                'role' => 'field_agent',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مشرف التنفيذ الى حالة يتم التنفيذ',
                'created_at' => '2025-08-14 10:07:53',
                'updated_at' => '2025-08-14 10:07:53',
            ],
            [
                'id' => 17,
                'complaint_id' => 3,
                'from_status' => 'تم التعيين',
                'to_status' => 'يتم التنفيذ',
                'changed_by' => 17,
                'role' => 'field_agent',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مشرف التنفيذ الى حالة يتم التنفيذ',
                'created_at' => '2025-08-14 10:07:59',
                'updated_at' => '2025-08-14 10:07:59',
            ],
            [
                'id' => 18,
                'complaint_id' => 5,
                'from_status' => 'تم التعيين',
                'to_status' => 'يتم التنفيذ',
                'changed_by' => 17,
                'role' => 'field_agent',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مشرف التنفيذ الى حالة يتم التنفيذ',
                'created_at' => '2025-08-14 10:08:04',
                'updated_at' => '2025-08-14 10:08:04',
            ],
            [
                'id' => 19,
                'complaint_id' => 1,
                'from_status' => 'يتم التنفيذ',
                'to_status' => 'منجز ',
                'changed_by' => 17,
                'role' => 'field_agent',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مشرف التنفيذ الى حالة منجز',
                'created_at' => '2025-08-14 10:08:10',
                'updated_at' => '2025-08-14 10:08:10',
            ],
            [
                'id' => 20,
                'complaint_id' => 3,
                'from_status' => 'يتم التنفيذ',
                'to_status' => 'منجز ',
                'changed_by' => 17,
                'role' => 'field_agent',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مشرف التنفيذ الى حالة منجز',
                'created_at' => '2025-08-14 10:08:16',
                'updated_at' => '2025-08-14 10:08:16',
            ],
            [
                'id' => 21,
                'complaint_id' => 3,
                'from_status' => 'منجز',
                'to_status' => 'مغلقة',
                'changed_by' => 17,
                'role' => 'government_admin',
                'notes' => 'سوف يتم تغيير حالة الشكوى من قبل مشرف المحافظة الى حالة مغلقة',
                'created_at' => '2025-08-14 10:08:21',
                'updated_at' => '2025-08-14 10:08:21',
            ],
        ]);
    }
}
