<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use App\Models\Project;
use Illuminate\Support\Str;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'id' => 3,
                'user_id' => 5,
                'image_id' => 27,
                'category_id' => 1,
                'location_id' => 12,
                'number_of_participant' => 25,
                'title' => 'إنارة شارع الميدان',
                'Execution_date' => null,
                'description' => 'حملة لتركيب أعمدة إنارة تعمل بالطاقة الشمسية في شارع الثورة لتحسين الأمان ليلاً وتقليل استهلاك الكهرباء.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-08-11 10:52:22',
                'updated_at' => '2025-08-11 10:52:22',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 4,
                'user_id' => 6,
                'image_id' => 28,
                'category_id' => 1,
                'location_id' => 13,
                'number_of_participant' => 30,
                'title' => 'إنارة الطريق الرئيسي',
                'Execution_date' => null,
                'description' => 'العمل على تركيب 10 أعمدة إنارة شمسية لتخفيف الحوادث ليلاً.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-06-11 10:59:07',
                'updated_at' => '2025-06-11 10:59:07',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 5,
                'user_id' => 7,
                'image_id' => 29,
                'category_id' => 1,
                'location_id' => 14,
                'number_of_participant' => 20,
                'title' => 'إنارة ممر المشاة في المهاجرين',
                'Execution_date' => null,
                'description' => 'مشروع إنارة ممرات المشاة بالطاقة الشمسية بهدف تسهيل التنقل ليلاً.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-06-11 11:01:36',
                'updated_at' => '2025-06-11 11:01:36',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 6,
                'user_id' => 4,
                'image_id' => 30,
                'category_id' => 1,
                'location_id' => 15,
                'number_of_participant' => 20,
                'title' => 'إنارة مواقف الباص في مشروع دمر',
                'Execution_date' => null,
                'description' => 'حملة لتأمين إنارة صديقة للبيئة في مواقف الباص لتوفير الأمان للركاب.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-06-11 11:03:20',
                'updated_at' => '2025-06-11 11:03:20',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 7,
                'user_id' => 6,
                'image_id' => 31,
                'category_id' => 1,
                'location_id' => 16,
                'number_of_participant' => 30,
                'title' => 'إنارة الطريق الفرعي في حي القابون',
                'Execution_date' => null,
                'description' => 'حملة لتأمين إنارة صديقة للبيئة في مواقف الباص لتوفير الأمان للركاب.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-07-11 11:10:13',
                'updated_at' => '2025-07-11 11:10:13',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 8,
                'user_id' => 7,
                'image_id' => 32,
                'category_id' => 1,
                'location_id' => 17,
                'number_of_participant' => 15,
                'title' => 'إنارة مدخل حي برزة',
                'Execution_date' => null,
                'description' => 'مبادرة لتركيب أعمدة إنارة شمسية عند مداخل الحي التي تعاني من الظلام',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-06-11 11:12:04',
                'updated_at' => '2025-06-11 11:12:04',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 9,
                'user_id' => 8,
                'image_id' => 33,
                'category_id' => 1,
                'location_id' => 18,
                'number_of_participant' => 20,
                'title' => 'إنارة ساحة الفحامة',
                'Execution_date' => null,
                'description' => ': حملة تطوعية لإنارة ساحة البلدة بالطاقة الشمسية لتجميل المكان وتعزيز الأمان.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-05-11 11:16:28',
                'updated_at' => '2025-05-11 11:16:28',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 10,
                'user_id' => 4,
                'image_id' => 34,
                'category_id' => 2,
                'location_id' => 19,
                'number_of_participant' => 20,
                'title' => 'تزيين دوار كفرسوسة',
                'Execution_date' => null,
                'description' => 'تزيين دوار كفرسوسة بالورود والدهان لتحسين المنظر العام.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-04-11 11:20:04',
                'updated_at' => '2025-04-11 11:20:04',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 11,
                'user_id' => 4,
                'image_id' => 35,
                'category_id' => 2,
                'location_id' => 20,
                'number_of_participant' => 40,
                'title' => 'إعادة تأهيل حديقة في حي المزة فيلات غربية',
                'Execution_date' => null,
                'description' => 'تنظيف وإصلاح المقاعد وزراعة الزهور في الحديقة العامة.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-07-11 11:24:55',
                'updated_at' => '2025-07-11 11:24:55',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 12,
                'user_id' => 10,
                'image_id' => 36,
                'category_id' => 2,
                'location_id' => 21,
                'number_of_participant' => 40,
                'title' => 'حملة تلوين الجدران في حي ركن الدين',
                'Execution_date' => null,
                'description' => 'تنظيف وإصلاح المقاعد وزراعة الزهور في الحديقة العامة.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-07-11 11:29:17',
                'updated_at' => '2025-07-11 11:29:17',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 13,
                'user_id' => 9,
                'image_id' => 37,
                'category_id' => 2,
                'location_id' => 22,
                'number_of_participant' => 35,
                'title' => 'تنظيف نهر بردى',
                'Execution_date' => null,
                'description' => 'إزالة القمامة من ضفاف النهر ضمن حملة بيئية مجتمعية.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-06-11 11:39:04',
                'updated_at' => '2025-06-11 11:39:04',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 14,
                'user_id' => 10,
                'image_id' => 38,
                'category_id' => 2,
                'location_id' => 23,
                'number_of_participant' => 45,
                'title' => 'زراعة الزهور في ساحة الأمويين',
                'Execution_date' => null,
                'description' => 'حملة تجميلية لزراعة الورود حول الساحة.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-06-11 11:41:42',
                'updated_at' => '2025-06-11 11:41:42',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 15,
                'user_id' => 11,
                'image_id' => 39,
                'category_id' => 2,
                'location_id' => 24,
                'number_of_participant' => 45,
                'title' => 'ازالة رموز النظام البائد',
                'Execution_date' => null,
                'description' => 'حملة تجميلية لزراعة الورود و ازالة رموز النظام البائد',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-06-11 11:46:02',
                'updated_at' => '2025-06-11 11:46:02',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 16,
                'user_id' => 9,
                'image_id' => 40,
                'category_id' => 3,
                'location_id' => 25,
                'number_of_participant' => 30,
                'title' => 'يوم خيري لدعم الأسر المحتاجة',
                'Execution_date' => null,
                'description' => 'تنظيم فعالية لتوزيع سلال غذائية وملابس على العائلات المحتاجة في حي القدم.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-06-11 11:49:59',
                'updated_at' => '2025-06-11 11:49:59',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 17,
                'user_id' => 10,
                'image_id' => 41,
                'category_id' => 3,
                'location_id' => 26,
                'number_of_participant' => 30,
                'title' => 'يوم طبي مجاني في حي الزاهرة',
                'Execution_date' => null,
                'description' => 'بالتعاون مع أطباء متطوعين، نقدم فحوصات واستشارات طبية مجانية.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-05-11 11:52:39',
                'updated_at' => '2025-05-11 11:52:39',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 18,
                'user_id' => 11,
                'image_id' => 42,
                'category_id' => 3,
                'location_id' => 27,
                'number_of_participant' => 20,
                'title' => 'إفطار جماعي للأيتام',
                'Execution_date' => null,
                'description' => 'إقامة يوم خيري يتضمن إفطارًا للأطفال الأيتام مع نشاطات ترفيهية وهدايا.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-08-11 11:55:15',
                'updated_at' => '2025-08-11 11:55:15',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 19,
                'user_id' => 5,
                'image_id' => 43,
                'category_id' => 3,
                'location_id' => 28,
                'number_of_participant' => 50,
                'title' => 'حملة تبرع بالدم في جامعة دمشق',
                'Execution_date' => null,
                'description' => 'دعوة للطلاب للتبرع بالدم لصالح مشفى المواساة بالتعاون مع بنك الدم الوطني.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-05-11 11:58:16',
                'updated_at' => '2025-05-11 11:58:16',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 20,
                'user_id' => 8,
                'image_id' => 44,
                'category_id' => 3,
                'location_id' => 29,
                'number_of_participant' => 50,
                'title' => 'توزيع وجبات ساخنة في جوبر',
                'Execution_date' => null,
                'description' => 'دعوة للطلاب للتبرع بالدم لصالح مشفى المواساة بالتعاون مع بنك الدم الوطني.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-08-11 12:01:08',
                'updated_at' => '2025-08-11 12:01:08',
                'is_promoted' => 0,
                'is_archived' => 0
            ],
            [
                'id' => 21,
                'user_id' => 8,
                'image_id' => 45,
                'category_id' => 3,
                'location_id' => 30,
                'number_of_participant' => 50,
                'title' => 'كسوة الشتاء في يلدا',
                'Execution_date' => null,
                'description' => 'حملة خيريّة لتوزيع ألبسة شتوية مستعملة بحالة جيدة على المحتاجين',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-07-11 12:04:15',
                'updated_at' => '2025-07-11 12:04:15',
                'is_promoted' => 1,
                'is_archived' => 0
            ],
            [
                'id' => 22,
                'user_id' => 8,
                'image_id' => 46,
                'category_id' => 3,
                'location_id' => 31,
                'number_of_participant' => 50,
                'title' => 'يوم نشاط ترفيهي لأطفال مرضى السرطان',
                'Execution_date' => null,
                'description' => 'فعاليات ترفيهية وتوزيع هدايا على الأطفال داخل مشفى البيروني.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-07-11 12:07:14',
                'updated_at' => '2025-07-11 12:07:14',
                'is_promoted' => 1,
                'is_archived' => 0
            ],
            [
                'id' => 23,
                'user_id' => 8,
                'image_id' => 47,
                'category_id' => 3,
                'location_id' => 32,
                'number_of_participant' => 50,
                'title' => 'حملة تشجير طريق المطار',
                'Execution_date' => null,
                'description' => 'زراعة 100 شجرة على جانبي طريق المطار لتحسين المنظر البيئي.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-05-11 12:09:56',
                'updated_at' => '2025-05-11 12:09:56',
                'is_promoted' => 1,
                'is_archived' => 0
            ],
            [
                'id' => 24,
                'user_id' => 8,
                'image_id' => 48,
                'category_id' => 4,
                'location_id' => 33,
                'number_of_participant' => 30,
                'title' => 'حملة خضراء في زملكا',
                'Execution_date' => null,
                'description' => 'زراعة 100 شجرة على جانبي طريق زملكا لتحسين المنظر البيئي.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-08-11 12:14:57',
                'updated_at' => '2025-08-11 12:14:57',
                'is_promoted' => 1,
                'is_archived' => 0
            ],
            [
                'id' => 25,
                'user_id' => 8,
                'image_id' => 49,
                'category_id' => 4,
                'location_id' => 34,
                'number_of_participant' => 30,
                'title' => 'حملة بيئية في حديقة النيربين',
                'Execution_date' => null,
                'description' => 'زراعة أشجار دائمة الخضرة في حديقة الحي الشرقي بمشاركة الأهالي.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-07-11 12:17:22',
                'updated_at' => '2025-07-11 12:17:22',
                'is_promoted' => 1,
                'is_archived' => 0
            ],
            [
                'id' => 26,
                'user_id' => 8,
                'image_id' => 50,
                'category_id' => 5,
                'location_id' => 35,
                'number_of_participant' => 40,
                'title' => 'ترميم مدرسة ابتدائية في جوبر',
                'Execution_date' => null,
                'description' => 'زراعة أشجار دائمة الخضرة في حديقة الحي الشرقي بمشاركة الأهالي.',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-05-11 12:20:13',
                'updated_at' => '2025-05-11 12:20:13',
                'is_promoted' => 1,
                'is_archived' => 0
            ],
            [
                'id' => 27,
                'user_id' => 8,
                'image_id' => 51,
                'category_id' => 5,
                'location_id' => 36,
                'number_of_participant' => 40,
                'title' => 'صيانة منازل متضررة في القابون',
                'Execution_date' => null,
                'description' => 'تقديم يد المساعدة لإعادة ترميم أسقف ونوافذ منازل الفقراء',
                'type' => 'مبادرة',
                'status' => 'تصويت',
                'created_by' => 'user',
                'created_at' => '2025-07-11 12:25:24',
                'updated_at' => '2025-07-11 12:25:24',
                'is_promoted' => 0,
                'is_archived' => 0
            ]

            ];


            // Simulate donations
            $donorCount = rand(5, 15);
            $totalDonated = 0;

        foreach ($projects as $project) {
            $type = ['مبادرة', 'حملة رسمية'][rand(0, 1)];
            $amount = rand(20, 100);
            $totalDonated += $amount;

            DB::table('projects')->insert([
                'user_id' => rand(1, 12),
                'image_id' => $project['image_id'],
                'category_id' => $project['category_id'],
                'location_id' => $project['location_id'],
                'number_of_participant' => $project['number_of_participant'],
                'title' => $project['title'],
                'Execution_date' => Carbon::now()->addDays(rand(6, 30))->toDateString(),
                'description' => $project['description'],
                'type' => $type,
                'status' => $type === 'حملة رسمية' ? (rand(0, 1) ? 'نشطة' : 'منجزة') : 'تصويت',
                'created_by' => $project['created_by'],
                'created_at' => $project['created_at'],
                'updated_at' => $project['updated_at'],
                'is_promoted' => $project['is_promoted'],
                'is_archived' => $project['is_archived'],
            ]);
        }



    }
}
